# API's NBA

In [2]:
pip install nba_api

Requirement already satisfied: nba_api in c:\users\gabri\anaconda3\lib\site-packages (1.1.9)
Requirement already satisfied: requests in c:\users\gabri\anaconda3\lib\site-packages (from nba_api) (2.24.0)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\gabri\anaconda3\lib\site-packages (from requests->nba_api) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gabri\anaconda3\lib\site-packages (from requests->nba_api) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\gabri\anaconda3\lib\site-packages (from requests->nba_api) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\gabri\anaconda3\lib\site-packages (from requests->nba_api) (1.25.11)
Note: you may need to restart the kernel to use updated packages.

In [5]:
from nba_api.stats.static import teams
nba_teams = teams.get_teams()
nba_teams

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Atlanta',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'Golden State',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]

In [37]:
import pandas as pd
chaves = nba_teams[0].keys()
dicio_fin = {chave:[] for chave in chaves}
for dicio in nba_teams:
    for chave, valor in dicio.items():
        dicio_fin[chave].append(valor)
#print(dicio_fin)
df_nba = pd.DataFrame(dicio_fin)
df_nba.head(10)
# Warriors
warriors = df_nba[df_nba['nickname']== 'Warriors']
id_warriors = warriors['id'].values[0]

In [23]:
dicio = {chave:[] for chave in nba_teams[0]}
for time in nba_teams:
    for criterio, valor in time.items():
        dicio[criterio].append(valor)
df = pd.DataFrame(dicio)
df.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

In [40]:
from nba_api.stats.endpoints import leaguegamefinder
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=id_warriors)
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22020,1610612744,GSW,Golden State Warriors,0022000212,2021-01-18,GSW @ LAL,W,240,115,...,0.750,5.0,27.0,32.0,31,8,3,13,27,-2.0
1,22020,1610612744,GSW,Golden State Warriors,0022000177,2021-01-14,GSW @ DEN,L,240,104,...,0.708,5.0,38.0,43.0,29,9,4,19,25,-11.6
2,22020,1610612744,GSW,Golden State Warriors,0022000163,2021-01-12,GSW vs. IND,L,240,95,...,0.636,10.0,36.0,46.0,25,8,8,15,21,-3.6
3,22020,1610612744,GSW,Golden State Warriors,0022000148,2021-01-10,GSW vs. TOR,W,240,106,...,0.895,12.0,39.0,51.0,30,2,10,15,18,1.0
4,22020,1610612744,GSW,Golden State Warriors,0022000130,2021-01-08,GSW vs. LAC,W,240,115,...,0.833,9.0,29.0,38.0,25,13,3,15,19,0.2

In [60]:
import re
#Utilizando expressões regulares.
#Objetos dataframe tem, entre seus parametros o parametro str que é o conteúdo da coluna em si. Em seguida utilizamos o parametro contains
games.loc[(games['MATCHUP'].str.contains('GSW @ ...',regex = True)) & (games['PLUS_MINUS']>0)].sort_values('PLUS_MINUS', ascending = True)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
2158,21996,1610612744,GSW,Golden State Warriors,0029600954,1997-03-19,GSW @ MIA,L,265,91,...,0.697,11.0,36.0,47.0,11,5,4,19,24,0.4
1441,22005,1610612744,GSW,Golden State Warriors,0020501014,2006-03-23,GSW @ DAL,W,240,122,...,0.893,13.0,19.0,32.0,26,15,1,11,30,1.0
692,22013,1610612744,GSW,Golden State Warriors,0021300994,2014-03-16,GSW @ POR,W,241,113,...,0.818,10.0,31.0,41.0,17,7,7,12,29,1.0
426,12016,1610612744,GSW,Golden State Warriors,0011600063,2016-10-14,GSW @ DEN,W,265,129,...,0.667,11.0,41.0,52.0,27,10,11,16,22,1.0
462,22015,1610612744,GSW,Golden State Warriors,0021501190,2016-04-09,GSW @ MEM,W,239,100,...,0.923,7.0,41.0,48.0,20,3,7,11,14,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,22007,1610612744,GSW,Golden State Warriors,0020700916,2008-03-07,GSW @ MIA,W,239,134,...,0.750,14.0,37.0,51.0,26,12,3,9,21,35.0
409,22016,1610612744,GSW,Golden State Warriors,0021600202,2016-11-21,GSW @ IND,W,239,120,...,0.844,12.0,48.0,60.0,31,9,10,12,17,37.0
542,12015,1610612744,GSW,Golden State Warriors,0011500099,2015-10-22,GSW @ LAL,W,241,136,...,0.640,14.0,43.0,57.0,31,12,3,18,25,39.0
880,22012,1610612744,GSW,Golden State Warriors,1521200003,2012-07-13,GSW @ LAL,W,202,90,...,0.600,7.0,24.0,31.0,14,8,3,11,23,40.0
663,12014,1610612744,GSW,Golden State Warriors,0011400042,2014-10-12,GSW @ LAL,W,242,116,...,0.677,9.0,35.0,44.0,33,13,5,18,19,41.0